var namespace_bembel =
[
    [ "Basis", "namespace_bembel_1_1_basis.html", "namespace_bembel_1_1_basis" ],
    [ "GlueRoutines", "namespace_bembel_1_1_glue_routines.html", "namespace_bembel_1_1_glue_routines" ],
    [ "H2Multipole", "namespace_bembel_1_1_h2_multipole.html", "namespace_bembel_1_1_h2_multipole" ],
    [ "IO", "namespace_bembel_1_1_i_o.html", "namespace_bembel_1_1_i_o" ],
    [ "ProjectorRoutines", "namespace_bembel_1_1_projector_routines.html", "namespace_bembel_1_1_projector_routines" ],
    [ "AnsatzSpace", "class_bembel_1_1_ansatz_space.html", "class_bembel_1_1_ansatz_space" ],
    [ "Binomial", "struct_bembel_1_1_binomial.html", "struct_bembel_1_1_binomial" ],
    [ "Binomial< 0, 0 >", "struct_bembel_1_1_binomial_3_010_00_010_01_4.html", "struct_bembel_1_1_binomial_3_010_00_010_01_4" ],
    [ "Binomial< 0, N >", "struct_bembel_1_1_binomial_3_010_00_01_n_01_4.html", "struct_bembel_1_1_binomial_3_010_00_01_n_01_4" ],
    [ "Binomial< N, N >", "struct_bembel_1_1_binomial_3_01_n_00_01_n_01_4.html", "struct_bembel_1_1_binomial_3_01_n_00_01_n_01_4" ],
    [ "BlockClusterAdmissibility", "struct_bembel_1_1_block_cluster_admissibility.html", "struct_bembel_1_1_block_cluster_admissibility" ],
    [ "BlockClusterTree", "class_bembel_1_1_block_cluster_tree.html", "class_bembel_1_1_block_cluster_tree" ],
    [ "BlockClusterTreeParameters", "struct_bembel_1_1_block_cluster_tree_parameters.html", "struct_bembel_1_1_block_cluster_tree_parameters" ],
    [ "ClusterTree", "class_bembel_1_1_cluster_tree.html", "class_bembel_1_1_cluster_tree" ],
    [ "DifferentialForm", "struct_bembel_1_1_differential_form.html", "struct_bembel_1_1_differential_form" ],
    [ "DirichletTrace", "class_bembel_1_1_dirichlet_trace.html", "class_bembel_1_1_dirichlet_trace" ],
    [ "DiscreteLinearForm", "class_bembel_1_1_discrete_linear_form.html", "class_bembel_1_1_discrete_linear_form" ],
    [ "DiscreteOperator", "class_bembel_1_1_discrete_operator.html", "class_bembel_1_1_discrete_operator" ],
    [ "DiscreteOperatorComputer", "struct_bembel_1_1_discrete_operator_computer.html", null ],
    [ "DiscreteOperatorComputer< Eigen::H2Matrix< typename LinearOperatorTraits< Derived >::Scalar >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_h2_matrix_3_01typename_01_linear_ope625c1c1af22631c19398e86cea9e13d0.html", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_h2_matrix_3_01typename_01_linear_ope625c1c1af22631c19398e86cea9e13d0" ],
    [ "DiscreteOperatorComputer< Eigen::Matrix< Scalar, Eigen::Dynamic, Eigen::Dynamic >, Derived >", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_matrix_3_01_scalar_00_01_eigen_1_1_d3ab5fe988617dc61bfc63242dee3aaad.html", "struct_bembel_1_1_discrete_operator_computer_3_01_eigen_1_1_matrix_3_01_scalar_00_01_eigen_1_1_d3ab5fe988617dc61bfc63242dee3aaad" ],
    [ "DiscretePotential", "class_bembel_1_1_discrete_potential.html", "class_bembel_1_1_discrete_potential" ],
    [ "DummyOperator", "class_bembel_1_1_dummy_operator.html", "class_bembel_1_1_dummy_operator" ],
    [ "ElementTree", "class_bembel_1_1_element_tree.html", "class_bembel_1_1_element_tree" ],
    [ "ElementTreeMemory", "struct_bembel_1_1_element_tree_memory.html", "struct_bembel_1_1_element_tree_memory" ],
    [ "ElementTreeNode", "class_bembel_1_1_element_tree_node.html", "class_bembel_1_1_element_tree_node" ],
    [ "FunctionEvaluator", "class_bembel_1_1_function_evaluator.html", "class_bembel_1_1_function_evaluator" ],
    [ "FunctionEvaluatorEval", "struct_bembel_1_1_function_evaluator_eval.html", null ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Continuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_continuous_00_01_lin_op_01_4" ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::Discontinuous, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_discontinuous_00_01_lin_op_01_4" ],
    [ "FunctionEvaluatorEval< Scalar, DifferentialForm::DivConforming, LinOp >", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4.html", "struct_bembel_1_1_function_evaluator_eval_3_01_scalar_00_01_differential_form_1_1_div_conforming_00_01_lin_op_01_4" ],
    [ "GaussLegendreRule", "struct_bembel_1_1_gauss_legendre_rule.html", "struct_bembel_1_1_gauss_legendre_rule" ],
    [ "GaussLegendreRule< 0 >", "struct_bembel_1_1_gauss_legendre_rule_3_010_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_010_01_4" ],
    [ "GaussLegendreRule< 1 >", "struct_bembel_1_1_gauss_legendre_rule_3_011_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_011_01_4" ],
    [ "GaussLegendreRule< 10 >", "struct_bembel_1_1_gauss_legendre_rule_3_0110_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0110_01_4" ],
    [ "GaussLegendreRule< 11 >", "struct_bembel_1_1_gauss_legendre_rule_3_0111_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0111_01_4" ],
    [ "GaussLegendreRule< 12 >", "struct_bembel_1_1_gauss_legendre_rule_3_0112_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0112_01_4" ],
    [ "GaussLegendreRule< 13 >", "struct_bembel_1_1_gauss_legendre_rule_3_0113_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0113_01_4" ],
    [ "GaussLegendreRule< 14 >", "struct_bembel_1_1_gauss_legendre_rule_3_0114_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0114_01_4" ],
    [ "GaussLegendreRule< 15 >", "struct_bembel_1_1_gauss_legendre_rule_3_0115_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0115_01_4" ],
    [ "GaussLegendreRule< 16 >", "struct_bembel_1_1_gauss_legendre_rule_3_0116_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0116_01_4" ],
    [ "GaussLegendreRule< 17 >", "struct_bembel_1_1_gauss_legendre_rule_3_0117_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0117_01_4" ],
    [ "GaussLegendreRule< 18 >", "struct_bembel_1_1_gauss_legendre_rule_3_0118_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0118_01_4" ],
    [ "GaussLegendreRule< 19 >", "struct_bembel_1_1_gauss_legendre_rule_3_0119_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0119_01_4" ],
    [ "GaussLegendreRule< 2 >", "struct_bembel_1_1_gauss_legendre_rule_3_012_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_012_01_4" ],
    [ "GaussLegendreRule< 20 >", "struct_bembel_1_1_gauss_legendre_rule_3_0120_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_0120_01_4" ],
    [ "GaussLegendreRule< 3 >", "struct_bembel_1_1_gauss_legendre_rule_3_013_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_013_01_4" ],
    [ "GaussLegendreRule< 4 >", "struct_bembel_1_1_gauss_legendre_rule_3_014_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_014_01_4" ],
    [ "GaussLegendreRule< 5 >", "struct_bembel_1_1_gauss_legendre_rule_3_015_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_015_01_4" ],
    [ "GaussLegendreRule< 6 >", "struct_bembel_1_1_gauss_legendre_rule_3_016_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_016_01_4" ],
    [ "GaussLegendreRule< 7 >", "struct_bembel_1_1_gauss_legendre_rule_3_017_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_017_01_4" ],
    [ "GaussLegendreRule< 8 >", "struct_bembel_1_1_gauss_legendre_rule_3_018_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_018_01_4" ],
    [ "GaussLegendreRule< 9 >", "struct_bembel_1_1_gauss_legendre_rule_3_019_01_4.html", "struct_bembel_1_1_gauss_legendre_rule_3_019_01_4" ],
    [ "GenericMatrix", "class_bembel_1_1_generic_matrix.html", "class_bembel_1_1_generic_matrix" ],
    [ "Geometry", "class_bembel_1_1_geometry.html", "class_bembel_1_1_geometry" ],
    [ "Glue", "class_bembel_1_1_glue.html", "class_bembel_1_1_glue" ],
    [ "HelmholtzSingleLayerOperator", "class_bembel_1_1_helmholtz_single_layer_operator.html", "class_bembel_1_1_helmholtz_single_layer_operator" ],
    [ "HelmholtzSingleLayerPotential", "class_bembel_1_1_helmholtz_single_layer_potential.html", "class_bembel_1_1_helmholtz_single_layer_potential" ],
    [ "LaplaceSingleLayerOperator", "class_bembel_1_1_laplace_single_layer_operator.html", "class_bembel_1_1_laplace_single_layer_operator" ],
    [ "LaplaceSingleLayerPotential", "class_bembel_1_1_laplace_single_layer_potential.html", "class_bembel_1_1_laplace_single_layer_potential" ],
    [ "LinearFormBase", "struct_bembel_1_1_linear_form_base.html", "struct_bembel_1_1_linear_form_base" ],
    [ "LinearFormTraits", "struct_bembel_1_1_linear_form_traits.html", "struct_bembel_1_1_linear_form_traits" ],
    [ "LinearFormTraits< DirichletTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_dirichlet_trace_3_01_scalar_t_01_4_01_4" ],
    [ "LinearFormTraits< RotatedTangentialTrace< ScalarT > >", "struct_bembel_1_1_linear_form_traits_3_01_rotated_tangential_trace_3_01_scalar_t_01_4_01_4.html", "struct_bembel_1_1_linear_form_traits_3_01_rotated_tangential_trace_3_01_scalar_t_01_4_01_4" ],
    [ "LinearOperatorBase", "struct_bembel_1_1_linear_operator_base.html", "struct_bembel_1_1_linear_operator_base" ],
    [ "LinearOperatorTraits", "struct_bembel_1_1_linear_operator_traits.html", null ],
    [ "LinearOperatorTraits< DummyOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_dummy_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_dummy_operator_01_4" ],
    [ "LinearOperatorTraits< HelmholtzSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_helmholtz_single_layer_operator_01_4" ],
    [ "LinearOperatorTraits< LaplaceSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_laplace_single_layer_operator_01_4" ],
    [ "LinearOperatorTraits< MaxwellSingleLayerOperator >", "struct_bembel_1_1_linear_operator_traits_3_01_maxwell_single_layer_operator_01_4.html", "struct_bembel_1_1_linear_operator_traits_3_01_maxwell_single_layer_operator_01_4" ],
    [ "MaxwellSingleLayerOperator", "class_bembel_1_1_maxwell_single_layer_operator.html", "class_bembel_1_1_maxwell_single_layer_operator" ],
    [ "MaxwellSingleLayerPotential", "class_bembel_1_1_maxwell_single_layer_potential.html", "class_bembel_1_1_maxwell_single_layer_potential" ],
    [ "Patch", "class_bembel_1_1_patch.html", "class_bembel_1_1_patch" ],
    [ "PotentialBase", "struct_bembel_1_1_potential_base.html", "struct_bembel_1_1_potential_base" ],
    [ "PotentialReturnScalar", "struct_bembel_1_1_potential_return_scalar.html", "struct_bembel_1_1_potential_return_scalar" ],
    [ "PotentialReturnScalar< double, double >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01double_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01double_01_4" ],
    [ "PotentialReturnScalar< double, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01std_1_1complex_3_01double_01_4_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01double_00_01std_1_1complex_3_01double_01_4_01_4" ],
    [ "PotentialReturnScalar< std::complex< double >, double >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01double_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01double_01_4" ],
    [ "PotentialReturnScalar< std::complex< double >, std::complex< double > >", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01std_1_1complex_3_01double_01_4_01_4.html", "struct_bembel_1_1_potential_return_scalar_3_01std_1_1complex_3_01double_01_4_00_01std_1_1complex_3_01double_01_4_01_4" ],
    [ "PotentialTraits", "struct_bembel_1_1_potential_traits.html", "struct_bembel_1_1_potential_traits" ],
    [ "PotentialTraits< HelmholtzSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_helmholtz_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_helmholtz_single_layer_potential_3_01_lin_op_01_4_01_4" ],
    [ "PotentialTraits< LaplaceSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_laplace_single_layer_potential_3_01_lin_op_01_4_01_4" ],
    [ "PotentialTraits< MaxwellSingleLayerPotential< LinOp > >", "struct_bembel_1_1_potential_traits_3_01_maxwell_single_layer_potential_3_01_lin_op_01_4_01_4.html", "struct_bembel_1_1_potential_traits_3_01_maxwell_single_layer_potential_3_01_lin_op_01_4_01_4" ],
    [ "Projector", "class_bembel_1_1_projector.html", "class_bembel_1_1_projector" ],
    [ "Quadrature", "struct_bembel_1_1_quadrature.html", "struct_bembel_1_1_quadrature" ],
    [ "QuadratureVector", "struct_bembel_1_1_quadrature_vector.html", "struct_bembel_1_1_quadrature_vector" ],
    [ "QuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", "struct_bembel_1_1_quadrature_vector_3_01_quadrature_rule_00_010_01_4" ],
    [ "RotatedTangentialTrace", "class_bembel_1_1_rotated_tangential_trace.html", "class_bembel_1_1_rotated_tangential_trace" ],
    [ "static_assertKlessseqN", "struct_bembel_1_1static__assert_klessseq_n.html", null ],
    [ "static_assertKlessseqN< true >", "struct_bembel_1_1static__assert_klessseq_n_3_01true_01_4.html", "struct_bembel_1_1static__assert_klessseq_n_3_01true_01_4" ],
    [ "SuperSpace", "struct_bembel_1_1_super_space.html", "struct_bembel_1_1_super_space" ],
    [ "TensorProductQuadratureVector", "struct_bembel_1_1_tensor_product_quadrature_vector.html", "struct_bembel_1_1_tensor_product_quadrature_vector" ],
    [ "TensorProductQuadratureVector< QuadratureRule, 0 >", "struct_bembel_1_1_tensor_product_quadrature_vector_3_01_quadrature_rule_00_010_01_4.html", "struct_bembel_1_1_tensor_product_quadrature_vector_3_01_quadrature_rule_00_010_01_4" ],
    [ "TreeLeaf", "class_bembel_1_1_tree_leaf.html", "class_bembel_1_1_tree_leaf" ],
    [ "VTKDomainExport", "class_bembel_1_1_v_t_k_domain_export.html", "class_bembel_1_1_v_t_k_domain_export" ],
    [ "VTKSurfaceExport", "class_bembel_1_1_v_t_k_surface_export.html", "class_bembel_1_1_v_t_k_surface_export" ]
];