var namespace_bembel_1_1_projector_routines =
[
    [ "_proj_info", "struct_bembel_1_1_projector_routines_1_1__proj__info.html", "struct_bembel_1_1_projector_routines_1_1__proj__info" ],
    [ "projector_matrixmaker_", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker__.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker__" ],
    [ "projector_matrixmaker_< Derived, DifferentialForm::Continuous >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_continuous_01_4" ],
    [ "projector_matrixmaker_< Derived, DifferentialForm::Discontinuous >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_discontinuous_01_4" ],
    [ "projector_matrixmaker_< Derived, DifferentialForm::DivConforming >", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4.html", "struct_bembel_1_1_projector_routines_1_1projector__matrixmaker___3_01_derived_00_01_differential_form_1_1_div_conforming_01_4" ]
];